### ISSUE TITLE
Autocompletion: no whitespace is added after edward when pressing tab

### ISSUE THREAD

**Issue by eugene-gurevich** [yext/edward#101]
Autocompletion as discussed here: http://engblog.yext.com/edward/autocompletion/
In bash on macOS Sierra, when typing edw + TAB, it autocompletes to edward but doesn't add a whitespace afterwards.

**Comment by theothertomelliott** [comment]
Autocompletion of the `edward` command is part of the shell, so outside of the configuration for edward itself.

Is there a situation where this is happening with group/service names?

**Comment by eugene-gurevich** [comment]
This was happening because I had a directory called "edward" in the root of
my repo so bash would get confused and not add the space. This is a
non-issue.
