### ISSUE TITLE
the build command does not support environement variables for now

### ISSUE THREAD

**Issue by ymolists** [yext/edward#111]
```
  "groups": [
    {
      "name": "ymo-hadoop",
      "env": [
        "HADOOP_VERSION=hadoop-2.6.0-cdh5.4.10",
        "HADOOP_CLUSTER=--config conf/conf000"
      ],
      "children": [
        "namenode-init",
        "namenode-server"
      ]
    }
  ],

    {
      "name": "namenode-works",
      "commands": {
        "build": "./hadoop-2.6.0-cdh5.4.10/bin/hdfs --config conf/conf000 namenode -format"
      }
    },
    {
      "name": "namenode-broken",
      "commands": {
        "build": "./${HADOOP_VERSION}/bin/hdfs --config conf/conf000 namenode -format"
      }
    },

```

I am not sure if build is supposed to inherit the environement variable from the groups definition but it is not currently while the launch command is fine. Moreover, what happens when multiple groups define dependency on the same service for the build and launch commands ? do the environment variables get merged ? is there a way you can point a single service to reference a set of env variables ?

**Comment by theothertomelliott** [comment]
The build step does not receive the environment variables you provide, certainly can add support for that.

For groups, the environment variables are only used for the services when they are launched as part of that group. So with:
`edward start ymo-hadoop`
Will pass ymo-hadoop's environment variables to the services.
`edward start namenode-works`
Will not.
