### ISSUE TITLE
generate config for all services

### ISSUE THREAD

**Issue by chemidy** [yext/edward#113]
If i launch edward generate on a directory with Dockerfiles and go services, edward generate only docker services.

It will be good to have options for choosing what kind of services we want to be genrated : 
edward generate go
edward generate docker
edward generate "target"
edward generate all

**Comment by theothertomelliott** [comment]
Thanks for raising this issue. Can you provide a listing for the directory you're having trouble with? Then we can discuss the best way it would handle it.

Regarding selection of types, the arguments to generate are currently reserved for selecting service names to be generated, but types could be added with a flag, such as:
edward generate --target go
edward generate --target docker
edward generate --target go --target docker
Would that achieve what you need?

**Comment by chemidy** [comment]
Yes flag --target is perfect for me. 

My structure is one repository with all my microservices : 
/
/myuservice1/
/myservice1/Dockerfile
/myservice1/cmd/service1/main.go
/myservice2/
/myservice2/Dockerfile
/myservice1/cmd/service2/main.go

**Comment by theothertomelliott** [comment]
Cool, so we just need to allow additional services to be added in subdirectories when one is found. Makes sense, will get on it!
