### ISSUE TITLE
generate create/assign group for services

### ISSUE THREAD

**Issue by chemidy** [yext/edward#114]
It will be useful for generate command if we can use a group name. If the group exist add new discovered services on it, else create a group with the group name.

edward generate --group mygroup

By the way combinated to the --target option previously discussed, we can generate a group for docker services, a group for go services, ....

edward generate --target docker --group mydockergroup
edward generate --target go --group mygogroup

**Comment by theothertomelliott** [comment]
Fixed for 1.8.4
