### ISSUE TITLE
cannot generate if edward.json file is empty

### ISSUE THREAD

**Issue by chemidy** [yext/edward#120]
if the config file edward.json is empty (created with a touch), it's impossible to use generate command, i think it will be nice to check if the file is empty and write a good configuration file with generate command. 

> Error: /Users/myPath/edward.json: could not parse config file: unexpected end of JSON input

**Comment by chemidy** [comment]
fixed i will push on my next commit.

**Comment by theothertomelliott** [comment]
Added a test with an empty file. seems to be working now.
