### ISSUE TITLE
add command pre_build

### ISSUE THREAD

**Issue by chemidy** [yext/edward#121]
Sometimes before building i have to launch some scripts . It will be nice to have this possibility to be sure everything is up to date before building. 

For example : 
- generate my config files
- update vendor dependcies
- launching protoc to generate go api for my grpc services 

`
            "commands": {
                "pre_build": ["./manage_dependencies.sh", "./generate_private_key.sh"],
                "build": "go install",
                "launch": "authserver"
            },
`

**Comment by theothertomelliott** [comment]
Is this something you'd want to run every time you built your service? What we've tended to do at Yext is to either great a build-only service as part of a group, or run our build with a Makefile / Bazel, and replace the build command in the service config.

**Comment by chemidy** [comment]
For now i have one service on my group who compile everything for all my services.
But if i restart only one service, it's not ok.
And not all my services need this kind of pre_build step, so it's easier to do that on the service definition.

**Comment by chemidy** [comment]
Yep this is border line, i will continue with Makefile and bazel.
