### ISSUE TITLE
status option to list groups only

### ISSUE THREAD

**Issue by chemidy** [yext/edward#124]
For now we can show all services started with edward.
If we start a lot of groups with 2 or 3 services for each group, it will be very cool to show groups only .

edward status --group

**Comment by theothertomelliott** [comment]
Would this show groups that current have all their services running, or would we include partial groups?

It should be possible to determine the group under which a service was started from its state file (or that information can be easily added).

**Comment by chemidy** [comment]
I think we need to know if some services are RUNNING / KO / STOP on the group with something like that :

GROUP          READY                                STATUS       START TIME 
mygroup1        1/1                                    RUNNING     2017-08-11 16:10:18       
mygroup2       1/3                                    ERR               2017-08-11 16:10:25
