### ISSUE TITLE
Use conditional requests for GitHub version checks

### ISSUE THREAD

**Issue by theothertomelliott** [yext/edward#132]
https://github.com/google/go-github#conditional-requests

**Comment by shorsher** [comment]
I wouldn't mind working on this for my first pull request.  Im fairly novice with Go, but would love to help!  Would you mind pointing me in the right direction?

**Comment by theothertomelliott** [comment]
Thanks for volunteering!

The checks in question are in the updates package on the develop branch:
https://github.com/yext/edward/blob/develop/updates/updates.go

We're using Google's Go Github client to pull the latest version for the repo. GitHub allows for sending an ETag with the request so it doesn't count against the rate limit if nothing's changed.

The link in the original post outlines how you can change the http transport for the GitHub client to support ETags. I think you'd also need to store the tag along with, or in place of the cached version.
