### ISSUE TITLE
service versioning in the config file

### ISSUE THREAD

**Issue by chemidy** [yext/edward#134]
Sometimes we need to start microservices V1.X.Y and V2.X.Y for regression testing.

It will be very nice to have a service versioning in the config file and chose which version can be launched.

A workaround is to defined a different name like service1.X.Y and service2.X.Y, but this is the same service just with different API version.

**Comment by theothertomelliott** [comment]
Sounds like a useful feature, could you provide an example of the separate version name and how you're handling versioning in the build (env variable, build flag)?

It could be that this would be best served by a more generic solution that allows modifying build parameters from the command line.
