### ISSUE TITLE
Desktop / IDE notification when a service crash

### ISSUE THREAD

**Issue by chemidy** [yext/edward#135]
It will be very nice to have Desktop / Ide notification when a service crash.

On macos : osascript -e 'display notification "message" with title "title" subtitle "subtitle"'

**Comment by theothertomelliott** [comment]
That's a nice command, didn't know you could do that!

I had some thoughts for the long term roadmap around this. Was thinking we could add a service to Edward that provides events of some sort for when services are built, restarted, stopped, etc. Then we could attach a UI application or IDE plugin to provide visual notifications and display state.

Any thoughts?

**Comment by chemidy** [comment]
Yep sounds good 👍 this is a nice roadmap.

This command line was just a quick & dirty feature
