### ISSUE TITLE
Restart services do not restart crashed services

### ISSUE THREAD

**Issue by chemidy** [yext/edward#136]
If i start 3 services and few minutes later a service crashes, if i execute restart only 2 services restart.

**Comment by theothertomelliott** [comment]
What would you say to adding a "Died" state for services that stopped without input from the user or the runner process?

**Comment by chemidy** [comment]
Yep, if a service dies, for now we have only running services on edward status, it would be so cool to have a died state/status, and by the way it will be possible on a restart command to restart this died service.

**Comment by theothertomelliott** [comment]
Died state is supported as of 1.8.8, and restart will include these services.
