### ISSUE TITLE
Add support for java spring boot services on config generate

### ISSUE THREAD

**Issue by chemidy** [yext/edward#137]
Spring Boot is one of most used framework for Java Microservices, i think it's a good feature to support spring boot service discovery with edward generate.

**Comment by theothertomelliott** [comment]
Can you provide a link to some documentation? Would need to read up on it a bit.

**Comment by chemidy** [comment]
You can check spring boot doc : https://spring.io/guides/gs/actuator-service/

and the code sample : https://github.com/spring-guides/gs-actuator-service

But basically,  just have to check a direcotry with pom.xml with 

```
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        ...
    </parent>
```

And if there is a pom with support for spring boot, check into the subdirectories src/main/resources/application.properties the properties  => server.port: 9000 and sometimes spring.application.name: Stores

To build service : 'mvn clean package' or 'mvn clean install' in the pom.xml directory
To start the service 'mvn spring-boot:run'

So we can have a config like that : 

```
{
            "name": "spring.application.name or directory name of service ",
            "description": "spring boot service $name",
            "path": "pom.xml directory",
            "commands": {
                "build": "mvn clean install",
                "launch": "mvn spring-boot:run"
            },
            "launch_checks": {
                "ports": [
                    $server.port
                ]
            }
        }
```
