### ISSUE TITLE
Add option to launch unit tests before launching service

### ISSUE THREAD

**Issue by chemidy** [yext/edward#138]
If Auto-restart on edits is enabled, it's very useful to have an option to execute unit tests before launching service. 

"commands": {
                "build": "go install",
                "test":"go test -short $$(go list ./... | grep -v /vendor/)",
                "launch": "userserver"
            },

**Comment by theothertomelliott** [comment]
This could be useful beyond just autorestart. Wondering whether we'd want to run tests on each build, or if that could slow down rapid iteration.
