### ISSUE TITLE
Better autocompletes

### ISSUE THREAD

**Issue by theindexer** [yext/edward#144]
Currently edward autocompletes all subcommands, services, and groups at once.

Would be nice to autocomplete subcommands only at the subcommand stage, then services/groups after.

Additionally, if it doesn't cause autocomplete lag, edward stop should only autocomplete running services.

Might have a go at it later.

**Comment by theothertomelliott** [comment]
Please do.

Note that I migrated Edward to cobra (https://github.com/spf13/cobra) a couple months ago, which doesn't handle autocomplete in the same way that cmd did, so the current implementation is a little hacky.
