### ISSUE TITLE
edward failing on a very simple file in macos (10.12.6) and go1.8.5

### ISSUE THREAD

**Issue by ymolists** [yext/edward#145]
```
./edward.json
{
  "services": [
    {
      "name": "test-init",
      "env": [
        "TEST_ENV=./build/conf000/etc/conf"
        ],
      "commands": {
        "launch": "./tail.sh"
      }
    }
  ]
}

./tail.sh
#!/bin/bash
(
  set -ex
  echo ${TEST_ENV}
  tail -f /dev/null
)

$edward -c test.json start test-init
test-init > Start:  [Failed] (15.945ms)
Could not read log
open /Users/ymolists/.edward/logs/test-init.log: no such file or directory
Original error:
service terminated prematurely
Cleanup > test-init > Stop:  [Warning] (22.007ms)
Not running

```

I am getting the above weird error on my mac book pro. The exact same file works fine on my linux ubuntu desktop. In both cases i am using go-1.8.5 to build edward and using latest edward 1.8.5

Is there a workaround or this is a known bug ?

**Comment by theothertomelliott** [comment]
Sorry to hear you're having trouble.

This service configuration shouldn't be working on Linux. Since you've not specified launch conditions, edward will wait until your service opens a listening port, which the script doesn't appear to be doing.

The error you're seeing suggests that there was an error trying to find/launch the script itself. You might get a little more info if you try executing the runner directly:

    $ edward run test-init

**Comment by ymolists** [comment]
Thank you so much for the quick answer. I tried putting a launch_checks as well as a echo the actual line from the script. There might be issues with referencing the actual script but i cannot tell since i cant see which script its trying to run.

```

{
  "services": [
    {
      "name": "test-init",
      "env": [
        "TEST_ENV=./build/conf000/etc/conf"
        ],
      "commands": {
        "launch": "./tail.sh"
      },
      "launch_checks": {
        "log_text": "Finished startup"
      }
    }
  ]
}

#!/bin/bash

(
  set -ex
  echo ${HADOOP_PREFIX}
  echo "Finished startup"
  tail -f /dev/null

  # // "path"
  # // "TEST_CWD=${PWD}",

)

---
$edward -c test.json run test-init
Error: : open : no such file or directory

```

**Comment by theothertomelliott** [comment]
Thanks for the update. Could you try explicitly specifying a path in the service config?
I'd also recommend checking the permissions on the script.

**Comment by ymolists** [comment]
It seems that [somewhere here](https://github.com/yext/edward/blob/master/config/load.go#L26) it expects the file name to always be edward.json. 

By simply renaming the above configuration from test.json to edward.json it started to work !

**Comment by theothertomelliott** [comment]
As it turns out, the main edward instance will pick up the alternate config. I've just pushed a change to the develop branch that fixes this problem.
