### ISSUE TITLE
Option to use local RabbitMQ

### ISSUE THREAD

**Issue by mkilpatrick** [yext/edward#34]
I know the use of local vs. office RabbitMQ has gone back and forth recently. It would be nice if there was a way to specify which to use (override default of office) on service starts. 

Perhaps if rabbitmq is started within a group then all services in that group should use the locally start one.

**Comment by theothertomelliott** [comment]
We can now add environment variables to groups, which permits specific groups to have local rabbitmq configured as required.

See the Thundersnow configuration for an example.
