### ISSUE TITLE
Stop all running services

### ISSUE THREAD

**Issue by slaterkid** [yext/edward#37]
It would cool to be able to stop all running services.

For example if development doesn't require anything to be running, bunch of local services could make memory-hogging IDEs like eclipse even more painful.

Maybe there's a way to do this already? Other than something like `edward status | awk '{print $2}' | grep -v -e '^$' | grep -v NAME | xargs edward stop`

**Comment by theothertomelliott** [comment]
`edward stop` without any arguments will stop everything already :)
