### ISSUE TITLE
open /Users/SamGavisHughson/.edward/logs/sites-storm-build.log: no such file or directory

### ISSUE THREAD

**Issue by samgh** [yext/edward#42]
Got this error when trying to build on my personal computer. Seems that the file doesn't exist and it is failing rather than creating the file

**Comment by theothertomelliott** [comment]
Can you provide details of the command(s) you were running?

**Comment by PaigePonzeka** [comment]
I just had something similar happen to me. on My personal computer just tried "edward start stormgrp" except the file does exist

**edward start stormgrp**
```
==== Build Phase ====
Building group:  stormgrp
Building haproxy...                               [No build]
Building admin2...                                [Failed]
python: can't open file 'tools/icbm/build.py': [Errno 2] No such file or directory
Error building stormgrp: exit status 2
```

but bplay admin2 works fine

**Comment by theothertomelliott** [comment]
Is your $ALPHA environment variable set?

Which directory were you in?

**Comment by PaigePonzeka** [comment]
That fixed me. #sorrySam

**Comment by thundersnow** [comment]
Just had a similar issue come up because of a syntax error in the launch command.

**Comment by samgh** [comment]
Just had a similar issue come up because of a syntax error in the launch command.

**Comment by theothertomelliott** [comment]
This has been fixed on the run_command branch
