### ISSUE TITLE
Change build/launch order when starting groups

### ISSUE THREAD

**Issue by mkilpatrick** [yext/edward#55]
When starting a group everything is first built before launching anything. This is super unfortunate when something at the end of the group fails, causing the next try to rebuild everything again. It would be great if each item performed build then launch, instead of build, build, build, etc then launch, launch, launch, etc.

This would allow only rebuilding/launching the smaller subset of service(s) that failed, while the successful ones stay running.

**Comment by theothertomelliott** [comment]
There's also been a suggestion to do the launch in parallel with subsequent builds to speed things up. Can probably do both these together.

**Comment by theothertomelliott** [comment]
The start command itself calls build then start for each of the services/groups provided to it. Groups implement an interface that provides both of those functions.

The best way to do this is probably to consolidate build and start into a single start function (possibly with a param for skipping the build phase).

If we still wanted to support building all first, we'd need to create a third-consolidated build/start function.
